cask_args appdir: '/Applications'

tap "nikitabobko/tap"

brew "antidote"
brew 'awscli'
#brew 'aws-iam-authenticator'
brew 'bat'
brew "cloudflared"
brew 'cmake'
brew 'fd'
brew 'fx'
brew 'fzf'
brew 'git'
brew "gemini-cli"
brew 'gh'
brew 'gnu-sed'
brew "grep"
brew "htop"
brew 'httpie'
brew 'jq'
brew "mise"
brew 'neovim'
brew 'openssl'
brew 'rename'
brew 'ripgrep'
brew 'starship'
brew 'tree'
brew 'vim'
brew "watch"
brew 'wget'
brew "yamllint"
brew 'zoxide'

cask 'aerospace'
cask "nikitabobko/tap/aerospace"
cask 'claude-code'
cask "docker-desktop"
cask 'font-jetbrains-mono-nerd-font'
#cask 'google-chrome'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'linear'
cask 'notion'
cask 'obsidian'
cask 'postman'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'visual-studio-code'
cask 'vlc'

