"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$directory$git_branch$character'
right_format = '$all'
command_timeout = 5000

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
style = "fg:pine"

[character]
success_symbol = '[❯](fg:iris)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'fg:gold'

[git_status]
style = 'fg:love'

[aws]
disabled = true

#[package]
#disabled = true

[nodejs]
style = 'fg:pine'
