#!/bin/zsh

# remove old dot files
echo "Removing old dot files"
rm ~/.zshrc
rm ~/.vimrc
rm ~/.gitconfig
rm -rf .vim
rm ~/.gitignore
rm ~/.iterm2_shell_integration.zsh

# link new dot files
echo "Installing new dot files"
ln -s ~/.dotfiles/zsh/zshrc.symlink ~/.zshrc
ln -s ~/.dotfiles/vim/vimrc.symlink ~/.vimrc
ln -s ~/.dotfiles/git/gitignore.symlink ~/.gitignore
ln -s ~/.dotfiles/git/gitconfig.symlink ~/.gitconfig
ln -s ~/.dotfiles/iterm2/iterm2_shell_integration.zsh.symlink ~/.iterm2_shell_integration.zsh

# install homebrew
echo "Installing homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap homebrew/bundle

# install brew packages
echo "Installing brew packages"
cd ~/.dotfiles/brew
brew bundle
cd -

